- hosts: all
  remote_user: pi
  become_method: sudo
  vars_prompt:
      - name: new_password
        prompt: "Enter the password you would like to use for the user pi"
        confirm: yes

  tasks:
    - name: backup shadow file
      copy:
        remote_src: yes
        src: /etc/shadow
        dest: /tmp/shadow
      become: yes

    - name: generate hash pass
      delegate_to: localhost
      command:  python -c "from passlib.hash import md5_crypt; import getpass; print (md5_crypt.hash('{{new_password}}'))"
      register: hash

    - debug:
        var: hash.stdout

    - name: update password
      user:
        name: pi
        password:  '{{hash.stdout}}'
      become: yes

