build:
    environment:
        python: 3.7.1

        variables:
            PYTHON_VERSIONS: '3.7.1 3.6.3'

    tests:
        override:
            - 'pyenv local $PYTHON_VERSIONS'
            - command: 'tox'
